### ISSUE TITLE
Ability to send automated monthly email newsletter to showcase new Latinas added

### ISSUE THREAD

**Issue by FrancesCoronel** [Latina-Dev/latina-dev#12]
Automate email newsletter so if there's even just 1 new Latina added, it will trigger a monthly email newsletter and be sent out to all users who opt into email notifs

**Comment by fernperezg97** [comment]
Since we're hoping that our platform takes off, I'm highly considering integrating a transactional email service as opposed to using Python's integrated SMTP module.

A few pros to using SMTP:
- Easy to set up
- Cost effective
- Platform agnostic

Cons to SMTP:
- Less secure
- No built-in analytics
- Longer send times
- Long-term maintenance and uptime burden

Pros of transactional service:
- Analytics
- Higher email delivery rates
- Faster email delivery speeds
- Scalability 
- Better for large volume of emails

Cons of transactional service:
- Slight learning curve potentially
- Third-party dependent
- Higher growth == higher cost

Now, I've been doing a little bit of research and I'm a little familiar with AWS and they seem to offer the best "bang for your buck" in the sense that they offer a free plan where you get up to 62,000 emails/month. I already have an AWS account and could set it up and start integrating the API into my code, but I wanted to check in and see if anyone has any thoughts, comments, questions, opinions?

¡Gracias chicas!

**Comment by FrancesCoronel** [comment]
Yep I agree a transactional email service makes sense

I've heard good things about mailgun and sendgrid but if you're familiar with the aws one, I think that's okay that we set it up there!

**Comment by EllaCodes4** [comment]
Yes, transactional! 👌🏽👩🏽‍💻

**Comment by fernperezg97** [comment]
AWS SES use case email sent at 3:39PM CST. Email details can be found below:

Hello Amazon AWS Team,

We appreciate you taking the time to review my request for production access. Only registered users will receive emails from us. Our website’s address is https://latina.dev/ and will be an open source website created with the following objective in mind:

Latina Dev is a free, open source website that will provide a number of different resources to its subscribers such as free resources for learning software development, a place for other Latina developers to connect and network, and monthly newsletters detailing new resources added and/or possible future events.

We currently are in the production stage. This means that we do not yet have emails, but are in the process of creating our platform and implementing a transactional email service. We intend to use AWS SES to provide weekly/monthly newsletters detailing free new resources for Latina developers to notably spread awareness of Latinas in tech, but to also give more Latinas the opportunity to become involved in software development through a supportive open source community platform. These emails will be obtained through LinkedIn connections, existing LinkedIn groups for Latinas in STEM, and through contacting organizations and communities focusing on uplifting and raising awareness of underrepresented peoples in tech. 

In accordance with the AWS documentation, we will use Amazon SNS to enable bounce, complaint, and unsubscribe notifications. Once notified of any bounced, complaint, or unsubscribe email action, invalid emails will be placed in the Account-Level Suppression List. This avoids delivery of newsletter emails to invalid email addresses or recipients no longer interested in receiving newsletter emails.

We will also reference the “Amazon SES using an AWS SDK” along with “Email format in Amazon SES” documentation to ensure the compliance of email content and format (as advised by AWS) to help us maintain a good email sending reputation.

Finally, if you require any additional information in order to grant us production access, please do not hesitate to contact me.

Best,
Fernanda Pérez Gutiérrez—Latina Dev Contributor

**Comment by fernperezg97** [comment]
AWS SES use case accepted with a sending quota of 50,000 messages per day and a maximum send rate of 14 messages per second.
