### ISSUE TITLE
Randomize order of members shown on page

### ISSUE THREAD

**Issue by latinadeveloper** [Latina-Dev/latina-dev#63]
## Is your feature request related to a problem? Please describe.
Display the members in a random order when a user goes to the members page. 

## Describe the solution you'd like
Currently users are being displayed in alphabetical order. 
Goal: So all members get a chance to be showcased on the front page. 

## Additional context

This feature will be supplemented when the search bar is implemented.

**Comment by FrancesCoronel** [comment]
@latinadeveloper We already have randomized member ordering on the homepage (/) so members do get a chance to be showcased on the primary page. 

On the members page (/members), we do sort by first name because there's a lot of people being displayed. Once we do have search and filter there, it will be a lot nicer though.
